'use strict'

/**
 * @param {Egg.Application} app - egg application
 */
module.exports = app => {
  const { router, controller } = app
  router.get('/', controller.home.index)
  router.post('/oj/upload', controller.upload.uploadImg)
  router.post('/oj/upload/uploadTestData', controller.upload.uploadTestData)
  router.post('/oj/account/login', controller.account.login)
  router.post('/oj/account/addUser', controller.account.addUser)
  router.get('/oj/account/getUserInfo', controller.account.getUserInfo)
  router.get('/oj/account/getUserList', controller.account.getUserList)
  router.get('/oj/account/deleteUser', controller.account.deleteUser)
  router.post('/oj/examList/addExam', controller.examList.addExam)
  router.post('/oj/examList/examEdit', controller.examList.examEdit)
  router.get('/oj/examList/getExamList', controller.examList.getExamList)
  router.get('/oj/examList/getExamInfo', controller.examList.getExamInfo)
  router.get('/oj/examList/examAnalysis', controller.examList.examAnalysis)
  router.post('/oj/round/runner', controller.round.runner)
  router.get('/oj/round/getRunnerStatus', controller.round.getRunnerStatus)
  router.post('/oj/classes/addClasses', controller.classes.addClasses)
  router.get('/oj/classes/getClassList', controller.classes.getClassList)
  router.get('/oj/classes/getClassInfo', controller.classes.getClassInfo)
  router.get('/oj/classes/deleteClass', controller.classes.deleteClass)
  router.get('/oj/classes/getClassesStudent', controller.classes.getClassesStudent)
  router.post('/oj/examinee/examineeAdd', controller.examinee.examineeAdd)
  router.post('/oj/examinee/examineeModify', controller.examinee.examineeModify)
  router.get('/oj/examinee/getExamineeAddInfo', controller.examinee.getExamineeAddInfo)
  router.get('/oj/examinee/getExamineeList', controller.examinee.getExamineeList)
  router.get('/oj/examinee/getExamineeInfo', controller.examinee.getExamineeInfo)
  router.get('/oj/examinee/deleteExaminee', controller.examinee.deleteExaminee)
  router.post('/oj/topic/topicModify', controller.topic.topicModify)
  router.get('/oj/topic/getTopicList', controller.topic.getTopicList)
  router.get('/oj/topic/getTopicInfo', controller.topic.getTopicInfo)
  router.get('/oj/topic/deleteTopic', controller.topic.deleteTopic)
  router.post('/oj/testData/gapTest', controller.testData.gapTest)
  router.get('/oj/testData/gapTestStatus', controller.testData.gapTestStatus)
  router.get('/oj/testData/getGapTestInfo', controller.testData.getGapTestInfo)
  router.get('/oj/testData/deleteGapTest', controller.testData.deleteGapTest)
  router.post('/oj/testData/gapTestSubmit', controller.testData.gapTestSubmit)
  router.post('/oj/testData/uploadProgramTest', controller.testData.uploadProgramTest)
  router.get('/oj/testData/getProgramTest', controller.testData.getProgramTest)
  router.get('/oj/testData/deleteProgramTest', controller.testData.deleteProgramTest)
  router.post('/oj/testData/programTest', controller.testData.programTest)
  router.post('/oj/ide/addIDEData', controller.ide.addIDEData)
  router.get('/oj/ide/getIDEData', controller.ide.getIDEData)
  router.get('/oj/examTopic/getExamTopicNum', controller.examTopic.getExamTopicNum)
  router.get('/oj/examTopic/getExamTransferTopic', controller.examTopic.getExamTransferTopic)
  router.get('/oj/examTopic/getExamTopicList', controller.examTopic.getExamTopicList)
  router.get('/oj/examTopic/getExamTopicInfo', controller.examTopic.getExamTopicInfo)
  router.post('/oj/examTopic/examTopicTransfer', controller.examTopic.examTopicTransfer)
  router.post('/oj/examTopic/modifyExamTopic', controller.examTopic.modifyExamTopic)
  router.get('/oj/examTopic/deleteExamTopic', controller.examTopic.deleteExamTopic)
  router.get('/oj/examTopic/getAllExamTopic', controller.examTopic.getAllExamTopic)
  router.get('/oj/grade/tfGrade', controller.grade.tfGrade)
  router.get('/oj/grade/selectGrade', controller.grade.selectGrade)
  router.get('/oj/grade/gapGrade', controller.grade.gapGrade)
  router.get('/oj/grade/programGrade', controller.grade.programGrade)
  router.get('/oj/grade/gradeExport/:examId', controller.grade.gradeExport)
}
